在iptables.sh添加本地ip变化检查
Aurora-Admin-Panel/backend pull request #28
Opened 2022-01-16 08:24 UTC by fishg

2022-01-16 08:30 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +ExecStart=/bin/bash /usr/local/bin/iptables.sh outipcheck 0
感觉这里用 /usr/bin/bash 会好一些

2022-01-16 08:40 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +$SUDO systemctl daemon-reload
这里统一放到 check_ipt_service 函数比较好，可以少执行一次 systemctl daemon-reload

2022-01-16 08:44 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +    echo "start out interface ip check, now is: $INET"
减少stdout信息的出现，可能会影响其他任务对stdout的判断

2022-01-16 08:49 UTC, fishg commented on ansible/project/files/iptables.sh
> +ExecStart=/bin/bash /usr/local/bin/iptables.sh outipcheck 0
这个我处理下

2022-01-16 08:50 UTC, fishg commented on ansible/project/files/iptables.sh
> +$SUDO systemctl daemon-reload
这个判断有bug，改了。不建议放一起，升级的时候有些任务已经执行好的不用重复做

2022-01-16 09:02 UTC, fishg commented on ansible/project/files/iptables.sh
> +    echo "start out interface ip check, now is: $INET"
注释了

2022-01-16 10:51 UTC, smartcatboy requested changes

2022-01-16 10:51 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +$SUDO systemctl enable iptables-outipcheck.service
这里不需要 enable iptables-outipcheck.service

2022-01-16 10:51 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +    ! systemctl is-enabled --quiet iptables-outipcheck.service > /dev/null 2>&1 && install_ipt_out_ip_check_service
需要判断 timer 是否 enabled 而不是 service，但是为了稳妥起见，需要判断 service 是否存在（也可以利用 systemctl is-enabled 判断）

2022-01-16 10:51 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +WantedBy=multi-user.target
timer 的 Install 节使用 WantedBy=timers.target 会好一点

2022-01-16 10:51 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +OnUnitActiveSec=60s
这里应该加入 OnBootSec= （建议也为 60s ），否则重启后 timer 不会触发 service

2022-01-16 10:51 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +ExecStart=/usr/local/bin/iptables.sh outipcheck 0
建议修改一下脚本的传参检验，不要额外传入无意义参数 0

2022-01-16 10:51 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +$SUDO systemctl start iptables-outipcheck.service
加入 OnBootSec= 后，应该不需要手动 start service

2022-01-16 10:51 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +                /usr/local/bin/iptables.sh forward $in_port $target_ip $target_port
此处直接调用函数即可

2022-01-16 10:51 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +                echo "fix outip from $outip to $INET, $in_port -> $target_ip:$target_port"
避免非必要的输出

2022-01-16 11:32 UTC, LeiShi1313 commented
多加的timer和service在[clean.sh](https://github.com/Aurora-Admin-Panel/backend/blob/main/ansible/project/files/clean.sh)也要进行清除

2022-01-16 11:46 UTC, fishg commented on ansible/project/files/iptables.sh
> +$SUDO systemctl enable iptables-outipcheck.service
不清楚timer和service关系这个设计，测试时不enable并且start是不会被timer安排的

2022-01-16 11:47 UTC, fishg commented on ansible/project/files/iptables.sh
> +ExecStart=/usr/local/bin/iptables.sh outipcheck 0
这里单纯不想改脚本

2022-01-16 11:49 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +$SUDO systemctl enable iptables-outipcheck.service
这是因为使用了 OnUnitActiveSec 的原因，当初次添加的时候，如果没有触发过，就会保持一直不触发，因此加入 OnBootSec= 可以保证立刻触发一次，也能保证重启后 timer 工作正常。

2022-01-16 11:51 UTC, fishg commented on ansible/project/files/iptables.sh
> +                /usr/local/bin/iptables.sh forward $in_port $target_ip $target_port
这里麻烦了，还缺了识别原来是tcp、udp还是all

2022-01-16 11:53 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +ExecStart=/usr/local/bin/iptables.sh outipcheck 0
因为这个 service 和 timer 一旦安装到中转机后，以后想要更新修改就基本没有机会了，建议还是规范化一下脚本的输入参数，以免后续的更新引入 bug。

2022-01-16 11:53 UTC, fishg commented on ansible/project/files/iptables.sh
> +$SUDO systemctl enable iptables-outipcheck.service
这个先留着吧，空了测试是是不是必要的

2022-01-16 11:54 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +                /usr/local/bin/iptables.sh forward $in_port $target_ip $target_port
那你直接调用脚本的话，会导致全部变成all

2022-01-16 11:55 UTC, fishg commented on ansible/project/files/iptables.sh
> +ExecStart=/usr/local/bin/iptables.sh outipcheck 0
说到这个，现在可能是有bug？每次修改iptable的转发，iptable.sh就会被覆盖一次

2022-01-16 11:57 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +ExecStart=/usr/local/bin/iptables.sh outipcheck 0
目前因为 iptable.sh 在快速迭代的过程中，为了保证用户机器的脚本是最新的，所以每次转发都会进行同步，以后会优化同步逻辑，只有在更新或重启容器后才会进行首次的同步。

2022-01-16 12:10 UTC, fishg commented on ansible/project/files/iptables.sh
> +ExecStart=/usr/local/bin/iptables.sh outipcheck 0
完整考虑最好还是有版本号检查机制

2022-01-16 12:14 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +ExecStart=/usr/local/bin/iptables.sh outipcheck 0
ansible 在同步文件的时候会先校验文件是不是相同的，相同会跳过传输的。

2022-01-16 12:35 UTC, smartcatboy commented on ansible/project/files/gost@.service
> +ExecStart=/bin/sh -c '/usr/local/bin/gost -C /usr/local/etc/gost/%i.json >/dev/null 2>&1'
写成这个即可：
ExecStart=/usr/local/bin/gost -C /usr/local/etc/gost/%i.json >/dev/null 2>&1

2022-01-16 12:38 UTC, smartcatboy commented on ansible/project/files/brook-template.service
> +RestartSec=2s
出错自动重启有必要加吗？

2022-01-16 13:06 UTC, fishg commented on ansible/project/files/gost@.service
> +ExecStart=/bin/sh -c '/usr/local/bin/gost -C /usr/local/etc/gost/%i.json >/dev/null 2>&1'
各种写法我都感受过了

2022-01-16 13:45 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +            in_port=$(echo $snat_info|awk -F'->' '{print $1}')
这三处是不是可以直接赋值为 LOCAL_PORT REMOTE_IP REMOTE_PORT

2022-01-16 13:53 UTC, smartcatboy commented on ansible/project/files/iptables.sh
> +                    TYPE=$(iptables  -t  nat  -nL --line-number|grep SNAT|grep "BACKWARD $in_port->" |awk '{print $3}')
这个可以直接返回 tcp 和 udp 的具体类型，可以考虑直接 for 循环依次添加不同类型。

2022-01-25 05:30 UTC, smartcatboy commented on ansible/project/files/gost@.service
> +ExecStart=/bin/sh -c '/usr/local/bin/gost -C /usr/local/etc/gost/%i.json >/dev/null 2>&1'
最近看源码，发现好像只会调用 template.service 来处理 app 的服务，这些配置应该是已经废弃了。

2022-01-31 03:31 UTC, closed without merging